---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

-----------------------------------------------------------------------
```{r warning=FALSE}
data("instacart")
insta_data = instacart %>%
  filter(department == "beverages") %>%
  mutate(reordered = recode(reordered, "1" = "Yes", "0" = "No"), 
         order_dow = recode(order_dow, "0" = "Sunday", "1" = "Monday", "2" = "Tuesday", 
                             "3" = "Wednesday", "4" = "Thursday", "5" = "Friday", "6" = "Saturday")) 
```

```{r warning=FALSE}
count = insta_data %>% 
  group_by(aisle) %>%
  summarize(reordered = n())
```
Column {data-width=650}
-----------------------------------------------------------------------

### Bar Chart 
* Number of times goods from each aisle were reorderd within the beverage department. 
```{r warning=FALSE}
count %>%
  plot_ly(x = ~aisle, y = ~reordered, color = ~aisle, type = "bar", text = ~aisle) %>%
  layout(xaxis = list(title = "Aisle Category"),
         yaxis = list(title = "Total items reordered"))
```

Column {data-width=350}
-----------------------------------------------------------------------
### Boxplot
* Distribution of each aisle being purchased across all hours of day.  
```{r warning=FALSE}
insta_data %>%
  plot_ly(x = ~aisle, y = ~order_hour_of_day, color = ~aisle, type = "box") %>%
layout(xaxis = list(title = "Aisle Category"),
         yaxis = list(title = "Hour of Day Ordered"))
```

### Line plot
*  Distribution of quantity of beverages ordered across a week
```{r warning=FALSE}

count2 = insta_data %>% 
  group_by(aisle, order_dow) %>%
  summarize(order_id = n())

```

```{r warning=FALSE}

count2 %>%
  plot_ly(x = ~order_dow, y = ~order_id, color = ~aisle, type = "scatter", mode = "lines+marks") %>%
layout(xaxis = list(title = "Day of Week"),
         yaxis = list(title = "Quantity Ordered"))
```